---
Rakefile:
  unmanaged: true
Gemfile:
  optional:
    ':development':
      - gem: 'rspec-puppet'
        platforms: ["mswin", "mingw", "x64_mingw"]
        version: '< 2.6.0'
    ':system_tests':
      - gem: beaker-testmode_switcher
        version: '~> 0.4'
      - gem: master_manipulator
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  test_script:
    - "'bundle exec puppet apply -e \"user {''Administrator'': ensure=>present, password => ''Th!s1sS#cur3@@@2129021'', groups=>[''Administrators''],}\" && exit 0'"
    - 'bundle exec rspec spec/unit spec/integration -fd -b'
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2013
      end: 'latest'
